// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVPhkkg8cq0WSs4g9VtpFpt2wlqnTF6tA',
    appId: '1:756278172531:android:4b23741096f1bb9b0d4306',
    messagingSenderId: '756278172531',
    projectId: 'runproof-95326',
    databaseURL: 'https://runproof-95326-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'runproof-95326.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw9D9w8U94MtjR8i_sqP75UN-57pv9U4w',
    appId: '1:756278172531:ios:4a52a710e12afce30d4306',
    messagingSenderId: '756278172531',
    projectId: 'runproof-95326',
    databaseURL: 'https://runproof-95326-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'runproof-95326.appspot.com',
    iosClientId: '756278172531-nk7k697h59tugp9fqamqdb1hi0elrgqp.apps.googleusercontent.com',
    iosBundleId: 'com.example.gbgVarvet',
  );
}
